baseURL = "/"
languageCode = "it-it"
DefaultContentLanguage = "it"
title = "Covid19Alessandria.help"
theme = "bootstrap"
enableRobotsTXT = true

[params]
    author = "lab121.org"
    description = "Un progetto per condividere informazioni e attivarsi a supporto dell'emergenza COVID19"
    footer = "Made with Love for Alessandria"
    images = ["images/banner/covid19alessandriahelp_banner_quadrato.png"]
    prodURL = "https://covid19alessandria.help"
	follow = "Seguici su"
	search = "Cerca"
	promoters = "Promotori"
	primopiano = "In primo piano"
	lastupdate = "Ultimi aggiornamenti"
	readmore = "Leggi di più"
	moreinterest = "Potrebbe interessarti anche"
	tel = "Tel"
	address = "Indirizzo"
	medicalsupport = "Supporto medico e psicologico"
	truncatewords = 120
	numbertopic = 3
	numberlastupdates = 9

[languages]
	[languages.it]
		languageName = "Italian"
		title = "Covid19Alessandria.help"
		weight = 10
		[languages.it.menu]
		    [[languages.it.menu.main]]
                identifier = "bisogni"
                name = "Vedi tutti i bisogni"
                url  = "/bisogni"
                weight = 1
            	title = "Bisogni"
            [[languages.it.menu.main]]
                identifer = "cibo"
                parent = "bisogni"
                name = "Cibo"
            	title = "Cibo"
                url  = "/bisogni/cibo"
                weight = 1
            [[languages.it.menu.main]]
                identifer = "salute"
                parent = "bisogni"
                name = "Salute"
            	title = "Salute"
                url  = "/bisogni/salute"
                weight = 2
            [[languages.it.menu.main]]
                identifer = "sostegnoeconomico"
                parent = "bisogni"
                name = "Sostegno economico"
            	title = "Sostegno economico"
                url  = "/bisogni/sostegno-economico"
                weight = 3
            [[languages.it.menu.main]]
                identifer = "informazioniutili"
                parent = "bisogni"
                name = "Informazioni utili"
            	title = "Informazioni utili"
                url  = "/bisogni/informazioni"
                weight = 4
            [[languages.it.menu.main]]
                identifer = "scuola"
                parent = "bisogni"
                name = "Scuola"
            	title = "Scuola"
                url  = "/bisogni/scuola"
                weight = 5
            [[languages.it.menu.main]]
                identifer = "quarantena"
                parent = "bisogni"
                name = "Supporto alla quarantena"
            	title = "Supporto alla quarantena"
                url  = "/bisogni/quarantena"
                weight = 6
            [[languages.it.menu.main]]
                identifier = "iniziative"
                name = "Vedi tutte le iniziative"
                url  = "/iniziative"
                weight = 2
            	title = "Iniziative"
            [[languages.it.menu.main]]
                identifer = "sportelli"
                parent = "iniziative"
                name = "Sportelli"
            	title = "Sportelli di ascolto e informativi"
                url  = "/iniziative/sportelli"
                weight = 1
            [[languages.it.menu.main]]
                identifer = "assistenza-persona"
                parent = "iniziative"
                name = "Assistenza alla persona"
            	title = "Assistenza alla persona"
                url  = "/iniziative/assistenza-alla-persona"
                weight = 2
            [[languages.it.menu.main]]
                identifer = "medico-psicologico"
                parent = "iniziative"
                name = "Supporto medico e psicologico"
            	title = "Supporto medico e psicologico"
                url  = "/iniziative/supporto-medico-psicologico"
                weight = 3
            [[languages.it.menu.main]]
                identifier = "archivio"
                name = "Archivio"
                url  = "/archivio"
                weight = 3
            	title = "Archivio"
            [[languages.it.menu.main]]
                identifier = "chi-siamo"
                name = "Chi siamo"
                url  = "/chi-siamo"
                weight = 4
            	title = "Chi siamo"
            [[languages.it.menu.main]]
                identifier = "partecipa"
                name = "Partecipa"
                url  = "/partecipa"
                weight = 5
            	title = "Partecipa"
            [[languages.it.menu.main]]
                identifier = "faq"
                name = "Faq"
                url  = "/faq"
                weight = 6
            	title = "FAQ"
	[languages.en]
		languageName = "English"
		title = "Covid19Alessandria.help"
		weight = 20
		[languages.en.params]
			description = "(inglese) Descrizione"
			follow = "Follow us"
			search = "Search"
			promoters = "Promoters"
			primopiano = "Important news"
			lastupdate = "Last updates"
			readmore = "Read more"
			moreinterest = "You could also be interested in"
			tel = "Phone"
			address = "Address"
			medicalsupport = "Medical and psychological support"
			prodURL = "https://covid19alessandria.help/en"
		[languages.en.menu]
			[[languages.en.menu.main]]
				identifier = "bisogni"
				name = "See all needs"
				url  = "/en/bisogni"
				weight = 1
				title = "Needs"
			[[languages.en.menu.main]]
				identifer = "cibo"
				parent = "bisogni"
				name = "Food"
				title = "Food"
				url  = "/en/bisogni/cibo"
				weight = 1
			[[languages.en.menu.main]]
				identifer = "salute"
				parent = "bisogni"
				name = "Health"
				title = "Health"
				url  = "/en/bisogni/salute"
				weight = 2
			[[languages.en.menu.main]]
				identifer = "sostegnoeconomico"
				parent = "bisogni"
				name = "Economic support"
				title = "Economic support"
				url  = "/en/bisogni/sostegno-economico"
				weight = 3
			[[languages.en.menu.main]]
				identifer = "informazioniutili"
				parent = "bisogni"
				name = "Useful information"
				title = "Useful information"
				url  = "/en/bisogni/informazioni"
				weight = 4
			[[languages.en.menu.main]]
				identifer = "scuola"
				parent = "bisogni"
				name = "School"
				title = "School"
				url  = "/en/bisogni/scuola"
				weight = 5
			[[languages.en.menu.main]]
				identifer = "quarantena"
				parent = "bisogni"
				name = "Quarantine support"
				title = "Quarantine support"
				url  = "/en/bisogni/quarantena"
				weight = 6
				
			[[languages.en.menu.main]]
				identifier = "iniziative"
				name = "See all initiatives"
				url  = "/en/iniziative"
				weight = 2
				title = "Initiatives"
			[[languages.en.menu.main]]
				identifer = "medico-psicologico"
				parent = "iniziative"
				name = "Medical and psychological support"
				title = "Medical and psychological support"
				url  = "/en/iniziative/supporto-medico-psicologico"
				weight = 3
					
			
			[[languages.en.menu.main]]
				identifier = "chi-siamo"
				name = "Who we are"
				url  = "/en/chi-siamo"
				weight = 4
				title = "Who we are"

	[languages.es]
		languageName = "Espanol"
		title = "Covid19Alessandria.help"
		weight = 30
		[languages.es.params]
			description = "(spagnolo) Descrizione"
			follow = "Síguenos"
			search = "Busca"
			promoters = "Promotores"
			primopiano = "En primer plano"
			lastupdate = "últimas actualizaciones"
			readmore = "Lee mas"
			moreinterest = "También te puede interesar"
			tel = "Tel"
			address = "Dirección"
			medicalsupport = "Apoyo médico y psicológico"
			prodURL = "https://covid19alessandria.help/es"
		[languages.es.menu]
			[[languages.es.menu.main]]
				identifier = "bisogni"
				name = "Mira todas las necesidades"
				url  = "/es/bisogni"
				weight = 1
				title = "Necesidades"
			[[languages.es.menu.main]]
				identifer = "cibo"
				parent = "bisogni"
				name = "Comida"
				title = "Comida"
				url  = "/es/bisogni/cibo"
				weight = 1
			[[languages.es.menu.main]]
                identifer = "informazioniutili"
                parent = "bisogni"
                name = "Información útil"
            	title = "Información útil"
                url  = "/es/bisogni/informazioni"
                weight = 4
			[[languages.es.menu.main]]
                identifer = "scuola"
                parent = "bisogni"
                name = "Escuela"
            	title = "Escuela"
                url  = "/es/bisogni/scuola"
                weight = 5

	[languages.fr]
		languageName = "Français"
		title = "Covid19Alessandria.help"
		weight = 40
		[languages.fr.params]
			description = "(francese) Descrizione"
			follow = "Suivez nous"
			search = "Rechercher"
			promoters = "Promoteurs"
			primopiano = "Au premier plan"
			lastupdate = "Dernières mises à jour"
			readmore = "Lire la suite"
			moreinterest = "Cela pourrait aussi vous intéresser"
			tel = "Tél"
			address = "Adresse"
			medicalsupport = "Soutien médical et psychologique"
			prodURL = "https://covid19alessandria.help/fr"
		[languages.fr.menu]
			[[languages.fr.menu.main]]
				identifier = "bisogni"
				name = "Voir tous les besoins"
				url  = "/fr/bisogni"
				weight = 1
				title = "Besoins"
			[[languages.fr.menu.main]]
				identifer = "cibo"
				parent = "bisogni"
				name = "Nourriture"
				title = "Nourriture"
				url  = "/fr/bisogni/cibo"
				weight = 1

[frontmatter]
    lastmod = [":fileModTime", ":default"]

[taxonomies]
    categoria = "categoria"

[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[params.algolia]
    vars = ["title"]
    params = []

[outputs]
    home = ["HTML", "RSS", "Algolia"]

[sitemap]
    changefreq = "monthly"
