baseURL = "/"
languageCode = "it-it"
DefaultContentLanguage = "it"
title = "Covid19Alessandria.help"
theme = "bootstrap"
enableRobotsTXT = true

[languages]
	[languages.it]
		languageName = "Italian"
		title = "Covid19Alessandria.help"
		weight = 10
	[languages.en]
		languageName = "English"
		title = "Covid19Alessandria.help English"
		weight = 20
		[languages.en.params]
			description = "(inglese) Descrizione"
			follow = "(inglese) Seguici su"
		[languages.en.menu]
			[[languages.en.menu.main]]
				identifier = "bisogni"
				name = "See all needs"
				url  = "bisogni"
				weight = 1
				title = "Needs"
			[[languages.en.menu.main]]
				identifer = "cibo"
				parent = "bisogni"
				name = "Food"
				title = "Food"
				url  = "bisogni/cibo"
				weight = 1
			[[languages.en.menu.main]]
				identifer = "salute"
				parent = "bisogni"
				name = "Health"
				title = "Health"
				url  = "/en/bisogni/salute"
				weight = 2
			[[languages.en.menu.main]]
				identifer = "sostegnoeconomico"
				parent = "bisogni"
				name = "Economic support"
				title = "Economic support"
				url  = "/en/bisogni/sostegno-economico"
				weight = 3
			[[languages.en.menu.main]]
				identifer = "informazioniutili"
				parent = "bisogni"
				name = "Useful information"
				title = "Useful information"
				url  = "/en/bisogni/informazioni"
				weight = 4
			[[languages.en.menu.main]]
				identifer = "scuola"
				parent = "bisogni"
				name = "School"
				title = "School"
				url  = "/en/bisogni/scuola"
				weight = 5
			[[languages.en.menu.main]]
				identifer = "quarantena"
				parent = "bisogni"
				name = "Quarantine support"
				title = "Quarantine support"
				url  = "/en/bisogni/quarantena"
				weight = 6
				
			[[languages.en.menu.main]]
				identifier = "iniziative"
				name = "See all activities"
				url  = "/en/iniziative"
				weight = 2
				title = "Activity"
			[[languages.en.menu.main]]
				identifer = "sportelli"
				parent = "iniziative"
				name = "(inglese) Sportelli"
				title = "(inglese) Sportelli"
				url  = "/en/iniziative/sportelli"
				weight = 1
			[[languages.en.menu.main]]
				identifer = "assistenza-persona"
				parent = "iniziative"
				name = "Personal care"
				title = "Personal care"
				url  = "/en/iniziative/assistenza-alla-persona"
				weight = 2
				
			[[languages.en.menu.main]]
				identifier = "chi-siamo"
				name = "Who we are"
				url  = "/en/chi-siamo"
				weight = 4
				title = "Who we are"

			[[languages.en.menu.main]]
				identifier = "partecipa"
				name = "Join us"
				url  = "/en/partecipa"
				weight = 5
				title = "Join us"
	[languages.es]
		languageName = "Espanol"
		title = "Covid19Alessandria.help Espanol"
		weight = 30
		[languages.es.params]
			description = "(spagnolo) Descrizione"
			follow = "(spagnolo) Seguici su"
		[languages.es.menu]
			[[languages.es.menu.main]]
				identifier = "bisogni"
				name = "(spagnolo) Vedi tutti i bisogni"
				url  = "bisogni"
				weight = 1
				title = "(spagnolo) Bisogni"
			[[languages.es.menu.main]]
				identifer = "cibo"
				parent = "bisogni"
				name = "(spagnolo) Cibo"
				title = "(spagnolo) Cibo"
				url  = "/es/bisogni/cibo"
				weight = 1
			[[languages.es.menu.main]]
				identifer = "salute"
				parent = "bisogni"
				name = "(spagnolo) Salute"
				title = "(spagnolo) Salute"
				url  = "/es/bisogni/salute"
				weight = 2
			[[languages.es.menu.main]]
				identifer = "sostegnoeconomico"
				parent = "bisogni"
				name = "(spagnolo) Sostegno economico"
				title = "(spagnolo) Sostegno economico"
				url  = "/es/bisogni/sostegno-economico"
				weight = 3
			[[languages.es.menu.main]]
				identifer = "informazioniutili"
				parent = "bisogni"
				name = "(spagnolo) Informazioni utili"
				title = "(spagnolo) Informazioni utili"
				url  = "/es/bisogni/informazioni"
				weight = 4
			[[languages.es.menu.main]]
				identifer = "scuola"
				parent = "bisogni"
				name = "Escuela"
				title = "Escuela"
				url  = "/es/bisogni/scuola"
				weight = 5
			[[languages.es.menu.main]]
				identifer = "quarantena"
				parent = "bisogni"
				name = "(spagnolo) Supporto alla quarantena"
				title = "(spagnolo) Supporto alla quarantena"
				url  = "/es/bisogni/quarantena"
				weight = 6
				
			[[languages.es.menu.main]]
				identifier = "iniziative"
				name = "(spagnolo) Vedi tutte le iniziative"
				url  = "iniziative"
				weight = 2
				title = "(spagnolo) Iniziative"
			[[languages.es.menu.main]]
				identifer = "sportelli"
				parent = "iniziative"
				name = "(spagnolo) Sportelli"
				title = "(spagnolo) Sportelli"
				url  = "/iniziative/sportelli"
				weight = 1
			[[languages.es.menu.main]]
				identifer = "assistenza-persona"
				parent = "iniziative"
				name = "(spagnolo) Assistenza alla persona"
				title = "(spagnolo) Assistenza alla persona"
				url  = "/iniziative/assistenza-alla-persona"
				weight = 2
				
			[[languages.es.menu.main]]
				identifier = "chi-siamo"
				name = "(spagnolo) Chi siamo"
				url  = "/chi-siamo"
				weight = 4
				title = "(spagnolo) Chi siamo"

			[[languages.es.menu.main]]
				identifier = "partecipa"
				name = "(spagnolo)Partecipa"
				url  = "/partecipa"
				weight = 5
				title = "(spagnolo) Partecipa"

[frontmatter]
    lastmod = [":fileModTime", ":default"]

[taxonomies]
    categoria = "categoria"

[params]
    author = "lab121.org"
    description = "Un progetto per condividere informazioni e attivarsi a supporto dell'emergenza COVID19"
    footer = "Made with Love for Alessandria"
    images = ["images/banner/covid19alessandriahelp_banner_quadrato.png"]
    prodURL = "https://covid19alessandria.help"
	follow = "Seguici su"

[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[params.algolia]
    vars = ["title"]
    params = []

[outputs]
    home = ["HTML", "RSS", "Algolia"]

[sitemap]
    changefreq = "monthly"
	
[menu]
[[menu.main]]
    identifier = "bisogni"
    name = "Vedi tutti i bisogni"
    url  = "/bisogni"
    weight = 1
	title = "Bisogni"
[[menu.main]]
    identifer = "cibo"
    parent = "bisogni"
    name = "Cibo"
	title = "Cibo"
    url  = "/bisogni/cibo"
    weight = 1
[[menu.main]]
    identifer = "salute"
    parent = "bisogni"
    name = "Salute"
	title = "Salute"
    url  = "/bisogni/salute"
    weight = 2
[[menu.main]]
    identifer = "sostegnoeconomico"
    parent = "bisogni"
    name = "Sostegno economico"
	title = "Sostegno economico"
    url  = "/bisogni/sostegno-economico"
    weight = 3
[[menu.main]]
    identifer = "informazioniutili"
    parent = "bisogni"
    name = "Informazioni utili"
	title = "Informazioni utili"
    url  = "/bisogni/informazioni"
    weight = 4
[[menu.main]]
    identifer = "scuola"
    parent = "bisogni"
    name = "Scuola"
	title = "Scuola"
    url  = "/bisogni/scuola"
    weight = 5
[[menu.main]]
    identifer = "quarantena"
    parent = "bisogni"
    name = "Supporto alla quarantena"
	title = "Supporto alla quarantena"
    url  = "/bisogni/quarantena"
    weight = 6
	
[[menu.main]]
    identifier = "iniziative"
    name = "Vedi tutte le iniziative"
    url  = "/iniziative"
    weight = 2
	title = "Iniziative"
[[menu.main]]
    identifer = "sportelli"
    parent = "iniziative"
    name = "Sportelli"
	title = "Sportelli"
    url  = "/iniziative/sportelli"
    weight = 1
[[menu.main]]
    identifer = "assistenza-persona"
    parent = "iniziative"
    name = "Assistenza alla persona"
	title = "Assistenza alla persona"
    url  = "/iniziative/assistenza-alla-persona"
    weight = 2
	
[[menu.main]]
    identifier = "archivio"
    name = "Archivio"
    url  = "/archivio"
    weight = 3
	title = "Archivio"
	
[[menu.main]]
    identifier = "chi-siamo"
    name = "Chi siamo"
    url  = "/chi-siamo"
    weight = 4
	title = "Chi siamo"

[[menu.main]]
    identifier = "partecipa"
    name = "Partecipa"
    url  = "/partecipa"
    weight = 5
	title = "Partecipa"

[[menu.main]]
    identifier = "faq"
    name = "Faq"
    url  = "/faq"
    weight = 6
	title = "FAQ"