baseURL = "/"
languageCode = "it-it"
DefaultContentLanguage = "it"
title = "Covid19Alessandria.help"
theme = "bootstrap"
enableRobotsTXT = true

[languages]
	[languages.it]
		languageName = "Italian"
		title = "Covid19Alessandria.help"
		weight = 10
	[languages.en]
		languageName = "English"
		title = "Covid19Alessandria.help English"
		weight = 20
		[languages.en.params]
			description = "(inglese) Descrizione"
			follow = "(inglese) Seguici su"
		[languages.en.menu]
			[[languages.en.menu.main]]
				identifier = "bisogni"
				name = "(inglese) Vedi tutti i bisogni"
				url  = "bisogni"
				weight = 1
				title = "(inglese) Bisogni"
			[[languages.en.menu.main]]
				identifer = "cibo"
				parent = "bisogni"
				name = "(inglese) Cibo"
				title = "(inglese) Cibo"
				url  = "/bisogni/cibo"
				weight = 1
			[[languages.en.menu.main]]
				identifer = "salute"
				parent = "bisogni"
				name = "(inglese) Salute"
				title = "(inglese) Salute"
				url  = "/bisogni/salute"
				weight = 2
			[[languages.en.menu.main]]
				identifer = "sostegnoeconomico"
				parent = "bisogni"
				name = "(inglese) Sostegno economico"
				title = "(inglese) Sostegno economico"
				url  = "/bisogni/sostegno-economico"
				weight = 3
			[[languages.en.menu.main]]
				identifer = "informazioniutili"
				parent = "bisogni"
				name = "(inglese) Informazioni utili"
				title = "(inglese) Informazioni utili"
				url  = "/bisogni/informazioni"
				weight = 4
			[[languages.en.menu.main]]
				identifer = "scuola"
				parent = "bisogni"
				name = "(inglese) Scuola"
				title = "(inglese) Scuola"
				url  = "/bisogni/scuola"
				weight = 5
			[[languages.en.menu.main]]
				identifer = "quarantena"
				parent = "bisogni"
				name = "(inglese) Supporto alla quarantena"
				title = "(inglese) Supporto alla quarantena"
				url  = "/bisogni/quarantena"
				weight = 6

[frontmatter]
    lastmod = [":fileModTime", ":default"]

[taxonomies]
    categoria = "categoria"

[params]
    author = "lab121.org"
    description = "Un progetto per condividere informazioni e attivarsi a supporto dell'emergenza COVID19"
    footer = "Made with Love for Alessandria"
    images = ["images/banner/covid19alessandriahelp_banner_quadrato.png"]
    prodURL = "https://covid19alessandria.help"
	follow = "Seguici su"

[outputFormats.Algolia]
    baseName = "algolia"
    isPlainText = true
    mediaType = "application/json"
    notAlternative = true

[params.algolia]
    vars = ["title"]
    params = []

[outputs]
    home = ["HTML", "RSS", "Algolia"]

[sitemap]
    changefreq = "monthly"
	
[menu]
[[menu.main]]
    identifier = "bisogni"
    name = "Vedi tutti i bisogni"
    url  = "/bisogni"
    weight = 1
	title = "Bisogni"
[[menu.main]]
    identifer = "cibo"
    parent = "bisogni"
    name = "Cibo"
	title = "Cibo"
    url  = "/bisogni/cibo"
    weight = 1
[[menu.main]]
    identifer = "salute"
    parent = "bisogni"
    name = "Salute"
	title = "Salute"
    url  = "/bisogni/salute"
    weight = 2
[[menu.main]]
    identifer = "sostegnoeconomico"
    parent = "bisogni"
    name = "Sostegno economico"
	title = "Sostegno economico"
    url  = "/bisogni/sostegno-economico"
    weight = 3
[[menu.main]]
    identifer = "informazioniutili"
    parent = "bisogni"
    name = "Informazioni utili"
	title = "Informazioni utili"
    url  = "/bisogni/informazioni"
    weight = 4
[[menu.main]]
    identifer = "scuola"
    parent = "bisogni"
    name = "Scuola"
	title = "Scuola"
    url  = "/bisogni/scuola"
    weight = 5
[[menu.main]]
    identifer = "quarantena"
    parent = "bisogni"
    name = "Supporto alla quarantena"
	title = "Supporto alla quarantena"
    url  = "/bisogni/quarantena"
    weight = 6
	
[[menu.main]]
    identifier = "iniziative"
    name = "Vedi tutte le iniziative"
    url  = "/iniziative"
    weight = 2
	title = "Iniziative"
[[menu.main]]
    identifer = "sportelli"
    parent = "iniziative"
    name = "Sportelli"
	title = "Sportelli"
    url  = "/iniziative/sportelli"
    weight = 1
[[menu.main]]
    identifer = "assistenza-persona"
    parent = "iniziative"
    name = "Assistenza alla persona"
	title = "Assistenza alla persona"
    url  = "/iniziative/assistenza-alla-persona"
    weight = 2
	
[[menu.main]]
    identifier = "archivio"
    name = "Archivio"
    url  = "/archivio"
    weight = 3
	title = "Archivio"
	
[[menu.main]]
    identifier = "chi-siamo"
    name = "Chi siamo"
    url  = "/chi-siamo"
    weight = 4
	title = "Chi siamo"

[[menu.main]]
    identifier = "partecipa"
    name = "Partecipa"
    url  = "/partecipa"
    weight = 5
	title = "Partecipa"

[[menu.main]]
    identifier = "faq"
    name = "Faq"
    url  = "/faq"
    weight = 6
	title = "FAQ"